// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOkS1HtXuZYXsACCMBQORBhWjHrbs5ytU',
    appId: '1:425945874087:web:0486589ad77c41240ae582',
    messagingSenderId: '425945874087',
    projectId: 'homeassist-7a84f',
    authDomain: 'homeassist-7a84f.firebaseapp.com',
    storageBucket: 'homeassist-7a84f.firebasestorage.app',
    measurementId: 'G-JE2W1FQZ1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdUKrIBTccbg2DrZDOV9djqOZvf9hlE0I',
    appId: '1:425945874087:android:45e6010e339572d90ae582',
    messagingSenderId: '425945874087',
    projectId: 'homeassist-7a84f',
    storageBucket: 'homeassist-7a84f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOkS1HtXuZYXsACCMBQORBhWjHrbs5ytU',
    appId: '1:425945874087:web:41d61c7beb2487600ae582',
    messagingSenderId: '425945874087',
    projectId: 'homeassist-7a84f',
    authDomain: 'homeassist-7a84f.firebaseapp.com',
    storageBucket: 'homeassist-7a84f.firebasestorage.app',
    measurementId: 'G-PCGR6Q5Y3C',
  );
}
